syscoin/pali-wallet

demo/yarn.lock
extension/manifest.json
extension/source/scripts/Background/index.ts

fix websites crashing when the user disables and re-enables the wallet using management api

fix enable/disable extension

---

extension/manifest.json
extension/source/containers/auth/Send/Confirm.tsx
extension/source/containers/auth/SiteTransaction/SiteTransaction.scss
extension/source/scripts/Background/controllers/ConnectionsController.ts
extension/source/scripts/Background/index.ts
extension/views/app.html

fix some connection issues with the websites in firefox

fix issues in firefox

---

extension/source/scripts/Background/controllers/AccountController.ts

Added estimateSysTxFee which will estimate the tx fee for sending sys, also added a fix to subtract the fee from the total when the user tries to use the "Max" button to send all of their sys balance in one go.

Add estimateSysTxFee. Fix "Max send sys failing".

---

extension/source/components/Icon/Icon.tsx
extension/source/containers/auth/Settings/views/CurrencyView/Currency.tsx
extension/source/web/e2e/tests/ChangeToTestNetwork.spec.js

Merged updates and fixed test error

fix: fixed test error and merged updates

---

source/containers/auth/Home/Panel/components/AssetDetails.tsx
source/containers/auth/Home/Panel/components/TransactionDetails.tsx
source/scripts/Background/controllers/AccountController.spec.ts
source/state/store.ts

Changed values in mockJson and implemented function in store

---

source/containers/common/Header/AccountHeader.tsx
source/hooks/useFormat.ts
source/hooks/useUtils.ts
source/tests/unit/useFormat.spec.ts
source/tests/unit/useUtils.spec.ts

useUtils and useFormat tests

---

source/hooks/useBrowser.ts
source/pages/App/index.tsx
source/pages/CreatePass/CreatePass.tsx
source/pages/Home/Panel/components/TransactionDetails.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/Send.tsx
source/pages/Settings/ConnectedSites.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/ConnectionsController.ts
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/index.ts
source/scripts/ContentScript/index.ts
source/utils/index.ts
source/utils/logger.ts

Logs update

---

package.json
source/scripts/Background/controllers/DAppController.ts
source/scripts/Provider/EthereumProvider.ts
yarn.lock

Feat: add functions in ethereumProvider

---

source/pages/Settings/Currency.tsx

Fix currency conversion

---

source/pages/Receive/Receive.tsx
source/pages/Settings/About.tsx
source/pages/Settings/AutoLock.tsx
source/pages/Settings/ConnectHardwareWallet.tsx
source/pages/Settings/ConnectedSites.tsx
source/pages/Settings/CreateAccount.tsx
source/pages/Settings/Currency.tsx
source/pages/Settings/CustomRPC.tsx
source/pages/Settings/DeleteWallet.tsx
source/pages/Settings/Phrase.tsx
source/pages/Settings/PrivateKey.tsx
source/pages/Settings/TrustedSites.tsx
views/app.html

change margin to 8 so it would not break the responsiveness

chore: change margin y from 12 to 8

---

.eslintrc.json
source/routers/ExternalRoute.tsx
source/scripts/Provider/EthereumProvider.ts

chore: add routes

---

source/components/Header/AccountHeader.tsx
source/components/Header/NormalHeader.tsx
source/pages/Home/Home.tsx
source/pages/Receive/Receive.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/Send.tsx
source/utils/transactions.ts

fix: solve address bug

---

manifest.json

Add `js/inpage.bundle.js` to the web accessible resources list at `manifest.json`

Fix sysmint connection

---

source/components/Layout/TxConfirmLayout.tsx
source/utils/format.ts

Update tx confirm layout data to uppercase

---

source/pages/Home/Panel/components/Details.tsx
source/scripts/Background/controllers/ControllerUtils.ts
yarn.lock

fix: solve assets details issue

---

source/pages/Send/Confirm.tsx
source/pages/Send/SendEth.tsx
source/utils/transactions.ts

fix: solve NaN balance bug

---

source/pages/Home/Panel/components/Details.tsx

chore: add transactions details structure in details file

---

source/pages/Settings/CustomRPC.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/utils.ts
source/types/transactions.ts

Fix custom rpc edition

---

.husky/pre-push
package.json

Lint staged update

---

.eslintrc.json
package.json
source/hooks/usePrice.ts
source/pages/Tokens/ImportToken.tsx
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/utils.ts
source/types/controllers.ts
tests/mocks.ts
yarn.lock

Replace coingecko client

---

source/scripts/Background/index.ts

Fix storage (sysweb3Di) setup

---

package.json
source/components/Header/NormalHeader.tsx
source/scripts/Background/controllers/MainController.ts
source/state/vault/index.ts
yarn.lock

fix: solve add rpc bug

---

source/pages/Settings/PrivateKey.tsx

fix: solve encrypted xprv issue

---

.github/workflows/main.yml
source/utils/format.spec.ts
tests/mocks.ts

chore: use gh secrets

---

source/components/Layout/TxConfirmLayout.tsx
source/components/Layout/TxLayout.tsx
source/pages/Connections/ConnectWallet.tsx
source/pages/Connections/ConnectedAccounts.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/SendEth.tsx
source/pages/Settings/ConnectHardwareWallet.tsx
source/pages/Settings/CustomRPC.tsx
source/pages/Tokens/ImportToken.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/index.ts
source/scripts/Background/controllers/transaction/syscoin.ts
source/scripts/Background/controllers/trezor/syscoin.ts
source/types/controllers.ts
source/types/transactions.ts

I commented the `TxLayout` and `TxConfirmLayout` declaration since its not implemented yet and was calling old functions

Controllers interfaces

---

source/components/Layout/TxConfirmLayout.tsx
source/components/Layout/TxLayout.tsx
source/pages/Connections/ConnectWallet.tsx
source/pages/Connections/ConnectedAccounts.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/SendEth.tsx
source/pages/Settings/ConnectHardwareWallet.tsx
source/pages/Settings/CustomRPC.tsx
source/pages/Tokens/ImportToken.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/index.ts
source/scripts/Background/controllers/transaction/syscoin.ts
source/scripts/Background/controllers/trezor/syscoin.ts
source/types/controllers.ts
source/types/transactions.ts

Reverts syscoin/pali-wallet#200

Revert "Controllers interfaces"

---

source/pages/Connections/ChangeAccount.tsx
source/pages/Connections/ConnectWallet.tsx
source/scripts/Background/controllers/DAppController.ts
source/scripts/Background/controllers/message-handler/index.ts
source/scripts/Background/index.ts
source/types/controllers.ts

Refactor dapp connect

---

source/pages/Connections/ConnectWallet.tsx
source/scripts/Background/controllers/DAppController.ts
source/types/controllers.ts

Fix dApp reconnect

---

source/scripts/Background/controllers/message-handler/requests.ts

Add `isConnected` check before calling provider methods

Protect method request

---

package.json
source/hooks/useStore.ts
source/pages/Send/Confirm.tsx
source/pages/Send/SendEth.tsx
source/pages/Send/SendSys.tsx
source/pages/Settings/Currency.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/state/vault/index.ts
source/state/vault/types.ts
source/types/controllers.ts
tests/unit/vaultStore.spec.ts
yarn.lock

fix any issues related to transactions functionalities, forms and validations

[wip] fix: tokens send

---

package.json
source/pages/Home/Panel/components/Details.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/SendEth.tsx
source/pages/Send/SendSys.tsx
source/pages/Settings/PrivateKey.tsx
yarn.lock

fix: decrypt xprv and open on explorer issue

---

source/scripts/Background/controllers/message-handler/requests.ts

Dapp 'isLocked' method

---

source/components/Header/NormalHeader.tsx

fix: solve glitch menu issue

---

source/pages/Settings/ConnectedSites.tsx
source/scripts/Background/controllers/DAppController.ts
source/types/controllers.ts
source/utils/network.ts

Connected sites

---

source/pages/Transactions/Transaction.tsx
source/pages/Transactions/TransactionConfirmation.tsx
source/pages/Transactions/index.tsx
source/routers/ExternalRoute.tsx
source/scripts/Provider/SysProvider.ts

[DApp] Set fee before send tx

---

source/scripts/Background/controllers/message-handler/requests.ts

Only allow disconnected dapps to call for 'wallet_isConnected'

Protect all methods except 'wallet_isConnected'

---

source/pages/Connections/ConnectWallet.tsx

Loading on account connect

---

source/components/Header/NormalHeader.tsx
source/utils/index.ts

Only display the connected status (green) when the dapp has a connection with the current account and network instead of any connection with pali

Fix connection indicator

---

source/components/Button/Button.tsx

fix: change font color

---

source/components/Header/NormalHeader.tsx
source/pages/Connections/ConnectWallet.tsx
source/pages/Home/Home.tsx
source/pages/Home/Panel/ActivityPanel.tsx
source/pages/Home/Panel/AssetsPanel.tsx
source/pages/Home/Panel/components/AssetDetails.tsx
source/pages/Home/Panel/components/Details.tsx
source/pages/Home/Panel/components/TransactionDetails.tsx
source/pages/Home/Panel/components/Transactions/List.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/Send.tsx
source/pages/Settings/ConnectedSites.tsx
source/pages/Settings/Currency.tsx
source/pages/Settings/ForgetWallet.tsx
source/pages/Tokens/AddToken.tsx
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/state/vault/index.ts
source/state/vault/types.ts
source/types/controllers.ts
source/utils/network.ts
source/utils/transactions.ts

don't update account if there is no wallet state changes

style: latest update

---

package.json
source/components/Header/NormalHeader.tsx
source/pages/Connections/ConnectWallet.tsx
source/pages/Home/Home.tsx
source/pages/Home/Panel/ActivityPanel.tsx
source/pages/Home/Panel/AssetsPanel.tsx
source/pages/Home/Panel/components/AssetDetails.tsx
source/pages/Home/Panel/components/Details.tsx
source/pages/Home/Panel/components/TransactionDetails.tsx
source/pages/Home/Panel/components/Transactions/List.tsx
source/pages/Import/CreatePass.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/Send.tsx
source/pages/Settings/About.tsx
source/pages/Settings/ConnectedSites.tsx
source/pages/Settings/Currency.tsx
source/pages/Settings/ForgetWallet.tsx
source/pages/Tokens/AddToken.tsx
source/routers/index.tsx
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/scripts/Background/index.ts
source/state/vault/index.ts
source/state/vault/types.ts
source/types/controllers.ts
source/utils/network.ts
source/utils/transactions.ts
yarn.lock

use a more reliable way to identify bitcoin based networks

fix: id bitcoin based networks

---

source/components/Header/NormalHeader.tsx
source/pages/Connections/ConnectWallet.tsx
source/pages/Home/Home.tsx
source/pages/Home/Panel/ActivityPanel.tsx
source/pages/Home/Panel/AssetsPanel.tsx
source/pages/Home/Panel/components/AssetDetails.tsx
source/pages/Home/Panel/components/Details.tsx
source/pages/Home/Panel/components/TransactionDetails.tsx
source/pages/Home/Panel/components/Transactions/List.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/Send.tsx
source/pages/Settings/ConnectedSites.tsx
source/pages/Settings/Currency.tsx
source/pages/Settings/ForgetWallet.tsx
source/pages/Tokens/AddToken.tsx
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/state/vault/index.ts
source/state/vault/types.ts
source/types/controllers.ts
source/utils/network.ts
source/utils/transactions.ts

style: currency page

---

package.json
source/components/Layout/Layout.tsx
source/hooks/useQuery.ts
source/pages/Connections/ConnectWallet.tsx
source/pages/Settings/ConnectedSites.tsx
source/pages/Transactions/Fee.tsx
source/pages/Transactions/Sign.tsx
source/pages/Transactions/Transaction.tsx
source/pages/Transactions/TransactionConfirmation.tsx
source/routers/ExternalRoute.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/index.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/scripts/Provider/SysProvider.ts
source/state/dapp/types.ts
source/utils/browser.ts
source/utils/network.ts
yarn.lock

dapp: minor fixes

---

source/pages/Transactions/Sign.tsx
source/pages/Transactions/TransactionConfirmation.tsx
source/scripts/Provider/SysProvider.ts

fix: display missing info in tx fields

---

source/pages/Send/Confirm.tsx

fix: remove header from fee and txs pages

---

source/scripts/Provider/SysProvider.ts

fix: add verifyAddress and zDag in tx data

---

source/scripts/Background/controllers/DAppController.ts
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/message-handler/types.ts
source/types/controllers.ts
source/utils/account.ts

Add missing dApp events

---

source/scripts/Provider/SysProvider.ts

fix: change method name

---

source/pages/Settings/ConnectedSites.tsx

This part of the code was left behind after changing how dapps interact with pali chain/account

Remove chain/account check on connected sites list

---

source/components/Layout/Layout.tsx
source/pages/Connections/ConnectWallet.tsx

fix: solve responsivity issue

---

source/components/Header/AccountHeader.tsx
source/pages/Home/Panel/AssetsPanel.tsx
source/pages/Home/Panel/components/Assets/EvmDetails.tsx
source/pages/Home/Panel/components/Assets/EvmList.tsx
source/pages/Home/Panel/components/Assets/SyscoinDetails.tsx
source/pages/Home/Panel/components/Assets/SyscoinList.tsx
source/pages/Send/SendEth.tsx
source/pages/Tokens/CustomToken.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/evm.ts
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Background/controllers/index.ts
source/state/vault/index.ts

fix: solve persist tokens issue

---

source/scripts/Background/controllers/account/syscoin.ts

fix: solve label persistence issue

---

package.json
source/pages/Transactions/TransactionConfirmation.tsx
source/scripts/Background/controllers/account/syscoin.ts
source/scripts/Provider/SysProvider.ts
yarn.lock

P.s.: This function only works with transferAssetOwnership implemented in sysweb3-keyring. Please, wait for this version before merge this branch.

feat: add transferAssetOwnership method in sys provider

---

source/components/Modal/Modal.tsx
source/pages/Settings/CustomRPC.tsx
source/pages/Settings/ManageNetwork.tsx
source/pages/Transactions/TransactionConfirmation.tsx
source/scripts/Background/controllers/MainController.ts
source/state/vault/index.ts
source/types/controllers.ts

fix: solve edit network bug

---

source/pages/Settings/CustomRPC.tsx
source/scripts/Background/controllers/MainController.ts

fix: change error message for sys UTXO network

---

source/pages/Transactions/TransactionConfirmation.tsx

fix: add tooltip in reduced info

---

source/pages/Start/Start.tsx

fix: change unlock behavior

---

source/pages/SeedConfirm/ConfirmPhrase.tsx
source/pages/SeedConfirm/index.tsx

fix: change wrong flow in seed validation process

---

source/components/Loading/Loading.tsx
source/pages/Home/Home.tsx
source/pages/Home/Panel/ActivityPanel.tsx

fix: solve react memory leaks issue

---

source/pages/Send/Confirm.tsx

fix: change fee type and use satoshi value

---

source/pages/Send/Confirm.tsx
source/pages/Send/SendNTokenTransaction.tsx
source/pages/Send/components/TransactionDetails.tsx

feat: enable copy and paste

---

source/components/Cards/Cards.tsx
source/pages/Settings/About.tsx

fix: solve DOM nesting issue

---

source/pages/Send/Confirm.tsx

fix: validate if tx was successfully completed or not

---

source/pages/Connections/ChangeConnectedAccount.tsx
source/scripts/Background/controllers/message-handler/requests.ts

fix: solve bug in switch account flow

---

source/pages/Home/Home.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/message-handler/types.ts
source/scripts/ContentScript/inject/paliProviderSyscoin.ts
source/utils/network.ts

feat: export isTestnet flag in window.pali

---

source/scripts/ContentScript/inject/paliProviderEthereum.ts
source/scripts/ContentScript/inject/paliProviderSyscoin.ts

fix: solve permanentlyDisconnected issue

---

source/pages/Send/SendSys.tsx
source/utils/transactions.ts

fix: solve send custom token bug in sys utxo network

---

source/pages/Send/SendSys.tsx

fix: solve ui issue in send page

---

source/pages/App/App.tsx

fix: solve fullscreen issue

---

source/components/Header/SetActiveAccountModal.tsx
source/pages/Connections/ChangeAccount.tsx
source/pages/Connections/ConnectWallet.tsx

fix: solve bypassing bug

---

source/constants/trustedApps.json
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/message-handler/types.ts
source/scripts/ContentScript/inject/paliProviderEthereum.ts
source/scripts/ContentScript/inject/paliProviderSyscoin.ts

feat: export data in window.ethereum and window.pali

---

source/constants/trustedApps.json
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/message-handler/types.ts
source/scripts/ContentScript/inject/paliProviderEthereum.ts
source/scripts/ContentScript/inject/paliProviderSyscoin.ts

Reverts syscoin/pali-wallet#376

Revert "feat: export data in window.ethereum and window.pali"

---

package.json
source/scripts/Background/controllers/MainController.ts
yarn.lock

fix: improve update trezor info perf

---

source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/evm.ts
source/scripts/Background/controllers/account/syscoin.ts

chore: replace setActiveAccountProperty to setAccountPropertyByIdAndType

---

source/scripts/Background/controllers/message-handler/requests.ts
source/scripts/ContentScript/inject/paliProviderEthereum.ts
source/scripts/ContentScript/inject/paliProviderSyscoin.ts

fix: add handleIsBitcoinBased _initializeState method

---

source/scripts/Background/controllers/message-handler/popup-promise.ts

fix: remove unnecessary dispatch

---

package.json
source/components/Header/SetActiveAccountModal.tsx
source/pages/Import/CreatePass.tsx
source/pages/Import/ImportPhrase.tsx
source/pages/Import/index.tsx
source/pages/SeedConfirm/index.tsx
source/pages/Start/Modal.tsx
source/pages/Start/Start.tsx
source/routers/ExternalRoute.tsx
source/routers/index.tsx
source/scripts/Background/controllers/MainController.ts
source/types/controllers.ts
yarn.lock

fix: solve security flaw in import account flow

---

source/scripts/Background/controllers/message-handler/requests.ts

feat: block content scripts for trezor wallet

---

source/scripts/Background/controllers/message-handler/requests.ts

fix: change wrong validation

---

source/scripts/Background/controllers/MainController.ts

fix: solve delayed info from provider

---

source/scripts/Background/controllers/transactions/utils.ts

fix: add confirmations property in tx object

---

source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/index.ts
source/scripts/Background/index.ts

fix: solve coingecko rate limit issue

---

source/pages/Settings/ExternalAddRPC.tsx
source/scripts/Background/controllers/MainController.ts

fix: solve bug in add network flow

---

source/pages/Send/SendNTokenTransaction.tsx
source/pages/Send/SendTransaction.tsx
source/utils/fetchGasAndDecodeFunction.ts

fix: solve estimate gas error

---

source/pages/Send/SendEth.tsx

fix: solve ui bug in sendEth component

---

source/scripts/Background/index.ts
source/scripts/ContentScript/index.ts
source/scripts/ContentScript/inject/handleWindowProperties.ts

fix: code structure improvement in add/remove eth prop flow

---

source/components/Modal/Modal.tsx
source/pages/Settings/Advanced.tsx

feat: implement confirmation modal in active advanced props flow

---

source/pages/Settings/ExternalWatchAsset.tsx
source/pages/Settings/index.ts
source/routers/ExternalRoute.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/account/evm.ts
source/scripts/Background/controllers/message-handler/popup-promise.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/types/controllers.ts
source/types/tokens.ts

feat: implement wallet_watchAsset method

---

source/scripts/Background/controllers/DAppController.ts

fix: allow user to remove connected sites

---

package.json
source/pages/Send/Approve.tsx
source/pages/Send/SendNTokenTransaction.tsx
source/pages/Settings/CustomRPC.tsx
source/scripts/Provider/EthProvider.ts
source/utils/fetchGasAndDecodeFunction.ts
yarn.lock

P.s.: Pay attention and test this PR with [feat/split-provider](https://github.com/pollum-io/sysweb3/pull/189) branch in sysweb3.

feat: replace web3Provider to contentScriptWeb3Provider in content scripts flow

---

source/scripts/Background/controllers/index.ts
source/state/vault/index.ts

chore: init new network state

---

source/scripts/Background/controllers/index.ts

chore: add optional chaining

---

package.json

chore: update pali version

---

manifest.json
source/pages/Import/ImportPhrase.tsx

fix: solve severe vulnerabilities in pali

---

source/pages/Home/Panel/components/Transactions/List.tsx
source/scripts/Background/controllers/transactions/types.ts
source/state/vault/index.ts
source/utils/transactions.ts

hotfix: remove unnecessary conditional

---

source/pages/Home/Panel/components/Transactions/List.tsx
source/state/vault/index.ts

fix: solve tx state management issue

---

manifest.json
package.json
yarn.lock

chore: update pali and sysweb3 version

---

manifest.json
package.json
source/assets/locales/en.json
source/assets/locales/es.json
source/components/Header/Menus/NetworkMenu.tsx
source/components/ToastAlert/ToastAlert.tsx
source/pages/Home/Panel/components/Details.tsx
source/pages/Send/Confirm.tsx
source/pages/Send/SendNTokenTransaction.tsx
source/pages/Send/SendSys.tsx
source/pages/Settings/ExternalWatchAsset.tsx
source/pages/Settings/ForgetWallet.tsx
source/pages/Settings/PrivateKey.tsx
source/pages/Tokens/SyscoinImport.tsx
yarn.lock

fix: solve spanish text issues and split fee

---

source/pages/Send/Confirm.tsx
source/pages/Send/SendNTokenTransaction.tsx
source/utils/network.ts

fix: solve eip1559 validation bug

---

source/pages/Receive/Receive.tsx

fix: solve infinity loading in receive page

---

source/pages/Send/Confirm.tsx

feat: implement message for ledger

---

source/pages/Connections/ConnectWallet.tsx
source/pages/Settings/ImportAccount.tsx

[clickup task](https://app.clickup.com/t/86a182kbq)

fix: solve UI bug in connect account page

---

source/scripts/ContentScript/inject/paliProviderSyscoin.ts

[task in clickup](https://app.clickup.com/t/86a18eg83)

feat: expose chainId in window.pali object

---

source/pages/Home/TxsPanel.tsx

style: changed radius from the right to left side

---

source/scripts/Provider/EthProvider.ts

fix: solve wrong behavior in chainge dapp

---

manifest.json
package.json
source/pages/Home/Panel/ActivityPanel.tsx
source/scripts/Background/controllers/index.ts

fix: solve state migration issue

---

source/components/Header/Menus/NetworkMenu.tsx

Bug: https://app.clickup.com/t/86a35d2we

fix: action zone on header

---

source/pages/Transactions/Sign.tsx

feat: add pathIn param in sys_sign method

---

source/pages/Settings/ManageAccounts.tsx

fix: Imported wallets do not appear in the managed accounts list

---

source/pages/Settings/ConnectHardwareWallet.tsx

fix: solve connection issue on ledger

---

source/pages/App/index.tsx
source/pages/Tokens/ImportToken.tsx
source/pages/Transactions/SignEth.tsx
source/routers/ExternalRoute.tsx
source/scripts/Background/controllers/MainController.ts
source/scripts/Background/controllers/index.ts
source/scripts/Background/controllers/message-handler/requests.ts
source/scripts/Background/index.ts
source/state/migrateWalletState.ts

fix: Error importing tokens

---

source/pages/Home/Panel/components/Assets/EvmDetails.tsx
source/pages/Home/Panel/components/Assets/EvmList.tsx
source/pages/Home/Panel/components/Nfts/EvmNftsList.tsx

86a50v7wg - fix: solve wrong behavior on NFT list

---

source/pages/Settings/Languages.tsx
source/scripts/Background/index.ts
source/utils/i18n.ts

https://github.com/syscoin/pali-wallet/issues/645

fix: adjust lng

---

source/pages/Home/Home.tsx
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/v3_0_1.ts
source/state/paliStorage.ts

fix: solve faucet modal bug

---

source/pages/Send/SendEth.tsx

fix: solve amount validation bug

---

source/pages/Send/SendEth.tsx

fix: solve bug in send tx [evm] page

---

source/scripts/Background/handlers/handleListeners.ts
source/scripts/Background/utils/startPolling.ts

fix: adjust polling

---

package.json
source/config/consts.js

chore: update pali version

---

manifest.json
package.json
source/components/Loading/Loading.tsx
source/config/consts.js
source/hooks/useNetworkChangeHandler.ts
source/pages/Chain/ChainErrorPage.tsx
source/pages/Connections/ChangeAccount.tsx
source/pages/Settings/SwitchEthereumChain.tsx
source/pages/Settings/SwitchNetworkUtxoEvm.tsx
source/routers/ExternalRoute.tsx
source/routers/useRouterLogic.ts
source/scripts/Background/controllers/message-handler/popup-promise.ts
source/scripts/Background/handlers/handleListeners.ts
source/scripts/Background/index.ts
source/scripts/ContentScript/index.ts
source/scripts/ContentScript/inject/paliProviderEthereum.ts

- inconsistent state between background and UI when opening extension
- problem setting the active window as closed in the state when clicking cancel or closing the popup
- keeps the extension background active

fixes several issues related to pali state
